# Generated by Django 4.2.1 on 2023-06-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_options_order_details_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categor_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='discount',
        ),
        migrations.DeleteModel(
            name='order_details',
        ),
        migrations.DeleteModel(
            name='order_item',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='product_category',
        ),
        migrations.DeleteModel(
            name='product_inventory',
        ),
    ]
