# Generated by Django 4.2.1 on 2023-06-03 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_phone_user_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('discount_percentage', models.IntegerField(blank=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.IntegerField()),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_inventory',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(upload_to='media/')),
                ('categor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_category')),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discount')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_inventory')),
            ],
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quanity', models.IntegerField(default=0)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order_details')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
