# Generated by Django 4.2.1 on 2023-06-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_discount_order_details_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_inventory',
            name='name',
            field=models.CharField(default='product_error', max_length=20),
        ),
    ]
