# Generated by Django 4.2.1 on 2023-06-04 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_inventory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_detial',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'Done')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='user_payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('O', 'ONLINE'), ('C', 'CASH')], max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='shopping_session',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.FloatField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cart_items',
            fields=[
                ('created_at', models.DateTimeField(auto_created=django.utils.timezone.now)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shopping_session')),
            ],
        ),
        migrations.AlterField(
            model_name='order_details',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.payment_detial'),
        ),
    ]
