# Generated by Django 4.2.1 on 2023-06-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_payment_detial_user_payment_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_payment',
            name='payment_type',
            field=models.CharField(choices=[('O', 'ONLINE'), ('C', 'CASH')], max_length=1),
        ),
    ]
