# Generated by Django 4.2.1 on 2023-06-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='desc',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='desc',
            field=models.TextField(max_length=100),
        ),
    ]
